apiVersion: apps/v1
kind: Deployment
metadata:
  name: cat
  labels:
    app: cat
  namespace: demo  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cat
  template:
    metadata:
      labels:
        app: cat
    spec:
      containers:
      - name: cat
        image: tho861998/cat
        ports:
        - containerPort: 8080
